### ISSUE TITLE
11月版のリリースお願いします

### ISSUE THREAD

**Issue by taishi-matsumura** [KingdomCraft-1/KingdomCraft#108]
[この辺](http://qiita.com/todogzm/items/db9f5f2cedf976379f84)とかを参考に、11月版のリリースをお願いします。
Releaseとか、なんかちょっとカッコイイやん？

とりあえず、先日masterに取り込んだコミットに「20161104」というタグだけ打っておきましたー
で、11月版のMilestoneが期限切れになっているので、Release作業が終わったら閉じてしまいましょう。

**Comment by Moto0116** [comment]
11月バージョンのリリースを作成したのでこのissue閉じときます。

**Comment by taishi-matsumura** [comment]
- 超ざっくりですが、リリース物の説明にChange logを書き足しておきました
- まだゲームとしては遊べないと思うので、Pre-releaseにしておきました
- 11月版のMilestoneも閉じておきました。進捗100%になっていて気持ちがいいですね！
