### ISSUE TITLE
セーブファイル管理クラスの設計と実装

### ISSUE THREAD

**Issue by Moto0116** [KingdomCraft-1/KingdomCraft#111]
ゲームのセーブファイルを管理するクラスの設計と実装

**Comment by Keitaro0408** [comment]
![savedatamanager](https://cloud.githubusercontent.com/assets/16873197/20587150/23b191f6-b24e-11e6-9373-e4d74070c278.png)

**Comment by Keitaro0408** [comment]
このクラスはデータの保存が必要な色々なクラスが持っていて、
書き込みと読み込みの際に各クラスからファイル書き込みがされるのでシングルトンクラスで作成する。

**Comment by Keitaro0408** [comment]
どこでファイルを読んでいるのか分かりづらいと思ったのでシングルトンはやめる

**Comment by Keitaro0408** [comment]
![savedatamanager](https://cloud.githubusercontent.com/assets/16873197/20699147/1cf1fcf8-b649-11e6-9d1e-2ca2d3933c1c.png)

**Comment by Keitaro0408** [comment]
完了したので閉じる
