### ISSUE TITLE
README更新して下さいね

### ISSUE THREAD

**Issue by taishi-matsumura** [KingdomCraft-1/KingdomCraft#112]
READMEが放置されている気がするので、ちょっとずつでも書き足しておいて下さいね。

ゲームの説明もさることながら、ビルド環境の説明(FBX SDKのバージョンとか)は欲しいです。
[ここ](https://github.com/puyoai/puyoai/blob/master/README.md)とか[ここ](https://github.com/s-nakaoka/choreonoid-doc/blob/master/ja/install/build-windows.rst)みたいに、GitHubで公開されている他のプロジェクトのREADMEを参考にすれば良いと思います。

そうしておけば、就活のときに企業に見せる資料としてこのリポジトリが丸ごと使えると思いますので頑張って！

**Comment by Moto0116** [comment]
確かにあのままなのはちょっと寂しいんで、早めに対応するようにします。

**Comment by taishi-matsumura** [comment]
スクショも貼ってあってステキ！！
継続して作業していく類のissueだと思うので、一旦closeします？

**Comment by Moto0116** [comment]
お願いします。
readmeの更新はmasterに機能がのる度にやりたいと思います。
