### ISSUE TITLE
READMEを更新する

### ISSUE THREAD

**Issue by Moto0116** [KingdomCraft-1/KingdomCraft#139]
READMEにsdkのバージョンやビルド環境などを記載する。

**Comment by taishi-matsumura** [comment]
VSのバージョンですが、2013ではなく2015？

**Comment by Moto0116** [comment]
作業はVisualStudio2013でやってます。
2015は使ってないです。

**Comment by taishi-matsumura** [comment]
僕のPCではキンクラだけ2015で開かれる…。
なんでやろ？

ちょっと調べてみまーす
