### ISSUE TITLE
Library配下のクラスのリファクタリングと修正

### ISSUE THREAD

**Issue by Moto0116** [KingdomCraft-1/KingdomCraft#145]
触っても影響でない今のうちにLibraryフォルダ配下のクラスをリファクタリングする。

**主な修正**
- in引数のポインタはconstをつける。
- ライブラリクラスの初期化はコンストラクタではなくInit関数を通してやるようにする。
- enumはできるだけクラス内で定義するようにする。
- クラス内で実装している関数はinlineを付ける。
- キャストを行う際はC++のキャストを使うようにする。
- プログラム内で使用している文字型をTCHAR系の型に統一する。
- vectorに関するkeyって名前の変数名をIndexに修正する。

**子issue**
 - [x] #149 
 - [x] #150  
 - [x] #154 
 - [x] #156
 - [x] #160 
 - [x] #161  
 - [x] #163   
 - [x] #165

**Comment by taishi-matsumura** [comment]
> 触っても影響でない今のうちにLibrarysフォルダ配下のクラスをリファクタリングする。

Librarys、スペルミスですねー

> - シングルトンクラスの初期化はコンストラクタではなくInit関数を通してやるようにする。

その意図は？

**Comment by Moto0116** [comment]
> Librarys、スペルミスですねー

すみません、Librarysは修正しときます…

> その意図は？

すみませんシングルトンクラスじゃなくてライブラリクラス全てのことでした…
それも修正します…
一応、理由はInit関数使う理由はコンストラクタでやると戻り値でのエラー判断ができないんで嫌ってだけです。

**Comment by Moto0116** [comment]
リファクタリングと修正は別に分けるつもりだったんですけど、手間が増えてしまうので、このissueを親にしてまとめます。

**Comment by Moto0116** [comment]
合流したので閉じる
