### ISSUE TITLE
GameObjectManagerクラスの設計と実装

### ISSUE THREAD

**Issue by Moto0116** [KingdomCraft-1/KingdomCraft#193]
GameObjectManagerクラスの設計と実装を行う

**Comment by Keitaro0408** [comment]
![0](https://cloud.githubusercontent.com/assets/16873197/21040412/18af57c6-be28-11e6-89f6-a156f571568e.png)

**Comment by Keitaro0408** [comment]
クラスの名前を間違えていたので上げ直し
![0](https://cloud.githubusercontent.com/assets/16873197/21047797/5045b7f8-be4f-11e6-94bf-9d6d40b77309.png)

**Comment by Keitaro0408** [comment]
**修正Version**
![0](https://cloud.githubusercontent.com/assets/16873197/21049881/b05b319e-be5a-11e6-8553-38a9515e1455.png)

**Comment by Keitaro0408** [comment]
完了したので閉じる
