### ISSUE TITLE
マイルストーン置いて下さい

### ISSUE THREAD

**Issue by taishi-matsumura** [KingdomCraft-1/KingdomCraft#24]
特にプレゼンとかのイベントが無いのでやり辛いのもわかりますが、やはり作業に何らかの期限はあった方が良いと思うのでMilestone置きましょう。
藤岡も同じような状況ですが、一応卒展に向けて3つくらいマイルストーン置いてます。(名前も「～1/E」とか適当ですが)
issueはmilestoneに紐付けておくと進捗率(issueの消化率)が出るのでけっこうわかりやすいですよ。
T戦は[こんな感じ](https://github.com/TeamT-SEN/T-SEN/milestones)。

**Comment by taishi-matsumura** [comment]
> 雑な名前ですがmilestoneを月ごとに作成して、現行のissueにも設定しておきました。

そんな感じで良いと思いますよ～。
一点確認なんですが、例えば「11月」ってマイルストーンの締切は11月30日では無くて11月1日ってことで合ってます？

**Comment by Moto0116** [comment]
それで合ってます。
11月までに実装するみたいなイメージだったんですけど、紛らわしいですか？

**Comment by taishi-matsumura** [comment]
個人的には「11月版」と言われると11月末のバージョンな気がしますが、全然問題無いですよ～
その月のバージョンは月初リリースってことで！！
閉じときまーす
