### ISSUE TITLE
アンダーバー絡みのシンボル名について

### ISSUE THREAD

**Issue by taishi-matsumura** [KingdomCraft-1/KingdomCraft#29]
C/C++ではアンダーバー始まりのシンボル名はコンパイラ用なので基本的に使用禁止です。
仮引数なんかに使うと見やすくて良いんですけどねー。
アンダーバーの後が小文字ならグローバル変数以外は大丈夫だった気もしますし、
旧ドラキンの頃から使われているので今さら直す必要は無いですが、
アンダーバー絡みは他にもNGのものがあるので再度周知のために書いておきます。

参考：
[競技プログラミングで陥りやすい言語仕様の罠](http://qnighy.github.io/informatics-olympiad/tip-language-trap.html)
[禁忌の識別子](http://cpp.aquariuscode.com/taboo-identifiers)

最後にチェックした人、issueをcloseしておいて下さい。
- [x] 森本
- [x] 小谷
- [x] 中地

**Comment by Moto0116** [comment]
アンダーバー始まりで大文字の仮引数がいくつかあったのでそれだけ修正しときます。
