### ISSUE TITLE
ソースファイルの文字コードについて

### ISSUE THREAD

**Issue by taishi-matsumura** [KingdomCraft-1/KingdomCraft#45]
@Yottomo SJISだとGitHubとかSourceTreeで文字化けしてイヤなのですが、普通は何に設定するものなんですか？

**Comment by taishi-matsumura** [comment]
了解です。
仕事では試行錯誤の末にUTF-8にしているのですが、UnityやってたときはUTF-16にしてた気もしたので聞いてみた次第です。
んー、いずれにせよいまどきSJISは無いですねぇ…

**Comment by taishi-matsumura** [comment]
ファイル名とか文字列扱ってるところでエラー出たりするので急ぎませんが、
ちょっとずつ文字コードをUTF-8に変えていきましょか。

**Comment by Moto0116** [comment]
- [ ] #49 
- [ ] #51
- [ ] #53 
- [ ] #55 
- [ ] #60

修正用のissueを切りました。
ちょっとずつやっていきます。

**Comment by Keitaro0408** [comment]
- [ ] #65 
- [ ] #66 
- [ ] #67 

修正用のissueを作成しました

**Comment by Moto0116** [comment]
@taishi-matsumura 全てのファイルをUTF-8に変更しましたので、確認お願いしていいですか？

**Comment by taishi-matsumura** [comment]
@Moto0116 
.hと.cppのうち、変更があったものと新規に追加されたものが全てUTF-8(BOM付き)になっていることを確認しました。
.fxと.hlslはSJISじゃないとダメなんでしたっけ？

**Comment by Moto0116** [comment]
.fxや.hlslはUTF-8(BOM付き)にするとコンパイルに失敗するので、そのままにしてます。
UTF-8(BOM無し)なら問題ないんですけど…

**Comment by taishi-matsumura** [comment]
VSのクソ仕様ですね。わかります。
うーん、だったらBOM無しのUTF-8にしちゃえば？

**Comment by Moto0116** [comment]
確かにその通りですね。
エフェクト関連のファイルはUTF-8(BOM無し)に修正しておきます。

**Comment by Keitaro0408** [comment]
分かりました。自分の担当した部分もUTF-8(BOM無し)に修正しておきます。
