### ISSUE TITLE
Doxyfile追加

### ISSUE THREAD

**Issue by Moto0116** [KingdomCraft-1/KingdomCraft#56]
Doxyfileを追加する

pull #57

**Comment by taishi-matsumura** [comment]
T-SENの方にも書いたのですが、

[ここ](http://cube.atnifty.com/~suzume/wiki/?develop%2Fdoxygen)とかを参考に、doxygenで生成したhtmlファイルをWindowsのヘルプファイル(chm)形式に変換すると捗ります。
読む人向けにchmを、作りたい人向けにdoxyfileを、それぞれリポジトリに入れておくと良いです。(あの大量の.jsとか.htmlとかは不要)

**Comment by Moto0116** [comment]
本線に合流したので閉じる

**Comment by taishi-matsumura** [comment]
chmファイル、ステキです。
classのbriefコメントも、「ｘｘｘクラス」程度でかまわないので書いてあると尚良いと思います。
クラス名だけでは何のクラスかわからないものは当然説明を書くべきです。

**Comment by Moto0116** [comment]
すみません、確かにそれでは説明不足でした。
修正用のissueを作成して対応します。
