### ISSUE TITLE
GameSceneクラスの設計と実装

### ISSUE THREAD

**Issue by Moto0116** [KingdomCraft-1/KingdomCraft#59]
GameSceneクラスの設計と実装を行う

**Comment by Keitaro0408** [comment]
![gamescene](https://cloud.githubusercontent.com/assets/16873197/20526034/92e53306-b105-11e6-8e4e-a14b18b2a9fd.png)
現在、中のクラス図を作成中です。
クラス図の作成が苦手なので、まだこれが必要じゃないか？という部分もあると思います。
確認お願いします。

**Comment by Moto0116** [comment]
UIManagerについてなんですが、各オブジェクトごとでUIを管理させるのではなくて、一括で管理してるのってなぜですか？

**Comment by Moto0116** [comment]
それとGameSceneのControlはSceneIDの返り値を持っているはずです。

**Comment by Keitaro0408** [comment]
>UIManagerについてなんですが、各オブジェクトごとでUIを管理させるのではなくて、一括で管理してるのってなぜですか？

例えば道敷設ボタンを押すときに建物建造ボタンがすでに押されているとその道一覧のメニューを消したりなど他のUIの影響を及ぼすという可能性があるのでここで管理しています。

**Comment by Keitaro0408** [comment]
>それとGameSceneのControlはSceneIDの返り値を持っているはずです。

自分の見落としでした。

**Comment by Keitaro0408** [comment]
![gamescene](https://cloud.githubusercontent.com/assets/16873197/20529681/631fa124-b114-11e6-8c21-ef433b98f8d8.png)

UIManagerについてSkypeで話し合った結果、学校で先生に意見を聞くことになったので明日はセーブデータを作るための文字解析の勉強をする

**Comment by Keitaro0408** [comment]
@Yottomo @taishi-matsumura  
クラス図の件についてなのですが、自分と森本が話し合った時、

自分はUIManagerで管理することでお互いのUI同士での動作がしやすくてGameScene等でバラバラになっているのがなくなって綺麗だと思いました。

森本はUIManagerでまとめるとオブジェクトと別れてしまいそことの処理が別れるから違うような気がする。
という考えでした。

最終的にUIManagerでも良いということになったのですが、先生方の場合UIはどのように設計しますか？

**Comment by taishi-matsumura** [comment]
もうちょい情報ちょうだい by @taishi-matsumura @takuto-danjo

**Comment by taishi-matsumura** [comment]
表示に関しては、個人的にはUIが勝手に情報集めて回る方が好きです。
各クラスが「あ、これUIに教えてあげなきゃ」ってのはちょっとめんどくさいので。
ただ、ポーリングで作っててUI起点で色々操作する場合が悩ましいですね。
イベント配信みたいな仕組みがあれば、各オブジェクトはUI起点かどうかなんて知ったこっちゃない作りにできるのですが…

**Comment by takuto000** [comment]
お疲れ様です
派遣されたたっくんです。
UIManagerですけどまずはStateManagerが気になりますね。
このクラス図だとStateManagerがStateを管理する為に各Managerが情報をGameSceneに返すorGameDataで持つ？(間違ってたらごめん)
となるとアクセッサだらけにならんのか？みたいな風に見えてしまうのでStateMachineにしてしまえばええんちゃうかって思ってしまう。

現在のStateのクラスを作り
各Stateクラスが必要なオブジェクトのインスタンスを持って処理すれば森本は納得するかな？(表示物全てをオブジェクトとしてStateクラスが持つとか。)
そんで今のStateクラスが押されたら走るイベントを定義してボタンとかにCallBackセットしてすりゃええ感じになるんじゃなかろうか。

**Comment by Keitaro0408** [comment]
お疲れ様です。
意見ありがとうございます。
StateManagerの動きについてなのですが自分の考えでは、状態を知る必要のある各クラスがStateManagerを持っており、ボタンが押された場合等で、その状態の変化をセットしてその状態次第で動作が変化するという感じです。

**Comment by taishi-matsumura** [comment]
うん、イベント配信みたいな大層な仕組みを作るまでいかなくても、
コールバック関数を登録しといて何かしら事象が発生したらそれが呼ばれる、
くらいの作りにはした方がいいかも知れませんね。
@Keitaro0408 の案でも動くものは作れるとは思うけど、「状態を知る必要のあるクラス」たちが
状態クラスにべーったり依存することになるよね？
クラス図的にはさほど差は無いかもですが、最初に一発「何かあったら呼んでね」って登録しておくだけなのと
「いまどうなってる？」って毎フレームチェックするのとでは、結合度が全然違うと思います。
そういう差を大事にする目線を持ってくれると嬉しいです。
その上で、ソースの改変しやすさや作業工数を鑑みて今の設計で進めるという結論になるのであれば
問題無いのではないかと思います。

**Comment by takuto000** [comment]
知るクラスが持ってるんだったらこのクラス図はおかしくないの？(あんまクラス図わからんけど･･)
知っているクラスに関連とかが付くべき？なのかなと思います。
多分他の人がクラス図見て意味わからんものが意味を成さないです。(間違ってたら土下座します)

**Comment by Keitaro0408** [comment]
すいません。
ゲームシーンの全体的なクラスを上げていなかったので伝わらなかったのだと思います。
一度削除してしまったのでコメントで作成途中ということを書き忘れていました
教えていただいたことを考慮してもう少し考え直してみます

**Comment by taishi-matsumura** [comment]
コールバック関数・関数ポインタ・関数オブジェクト(ファンクタ)などについて調べてみてください。
[このサイト](http://www.csg.ci.i.u-tokyo.ac.jp/~chiba/lecture/os/gui4.html)は順を追って説明してくれていてわかりやすかったです。

**Comment by Keitaro0408** [comment]
ありがとうございます。
参考にさせて頂きます。

**Comment by Keitaro0408** [comment]
![gamescene](https://cloud.githubusercontent.com/assets/16873197/20700286/cfe4968a-b64f-11e6-9d63-db010fc40f32.png)

**Comment by Keitaro0408** [comment]
終わったので閉じとく
