### ISSUE TITLE
Doxygenコメントの修正

### ISSUE THREAD

**Issue by Moto0116** [KingdomCraft-1/KingdomCraft#82]
Doxygenコメント修正の親issue
子のissueが閉じたら、こいつも閉じる。

- [x] #83
- [x] #84
- [x] #85
- [x] #86 
- [x] #87 
- [x] #88 
- [x] #89 
- [x] #90 
- [x] #91

**Comment by Keitaro0408** [comment]
issueの状態確認出来るしチェック要らなくない？

**Comment by Moto0116** [comment]
@Keitaro0408 参照がきれいに並んで見やすいのはたまたまやから、それに頼るのはダメやと思うんや。
今は子issueしかここに参照してないけど、どっかが参照するかもしれんわけやし。

**Comment by taishi-matsumura** [comment]
@Moto0116 一週間止まってるみたいなので、#86 終わらせちゃいましょか。

**Comment by Moto0116** [comment]
@taishi-matsumura 了解しました。適当に終わらせときます。

**Comment by taishi-matsumura** [comment]
このissueみたいに、関連するPRが大量に出るやつって、それ専用の親branch作ってそこからさらに作業branch作って、全部終わったら親branchごとdevelopにmergeするとかしたら散らからずに済むのかな？と思ったりした。

**Comment by Moto0116** [comment]
確かにそうですね。
親ブランチを間に挟んだらうまくいきそうですね。
機会があったら試してみたいと思います

**Comment by Moto0116** [comment]
子issueが全て閉じたので、こいつも閉じる。
